// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAjb1hZJPRzoy9hVZrJHgNSW47YbG--TY',
    appId: '1:925102029459:web:3ca99442e1849c0b60eb66',
    messagingSenderId: '925102029459',
    projectId: 'easy--learners',
    authDomain: 'easy--learners.firebaseapp.com',
    storageBucket: 'easy--learners.firebasestorage.app',
    measurementId: 'G-D8N0F3892E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvpR1cP2RFW9sWCoMK6oQ9RLyFuI0hERc',
    appId: '1:925102029459:android:40dc4f272b125b9e60eb66',
    messagingSenderId: '925102029459',
    projectId: 'easy--learners',
    storageBucket: 'easy--learners.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0cQtcqbEKBZWxKjdid7jbd0pCnmAvlA',
    appId: '1:925102029459:ios:bbf0e62e270cab6960eb66',
    messagingSenderId: '925102029459',
    projectId: 'easy--learners',
    storageBucket: 'easy--learners.firebasestorage.app',
    iosBundleId: 'com.example.easyLearners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0cQtcqbEKBZWxKjdid7jbd0pCnmAvlA',
    appId: '1:925102029459:ios:bbf0e62e270cab6960eb66',
    messagingSenderId: '925102029459',
    projectId: 'easy--learners',
    storageBucket: 'easy--learners.firebasestorage.app',
    iosBundleId: 'com.example.easyLearners',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAjb1hZJPRzoy9hVZrJHgNSW47YbG--TY',
    appId: '1:925102029459:web:38835ff2db978c4e60eb66',
    messagingSenderId: '925102029459',
    projectId: 'easy--learners',
    authDomain: 'easy--learners.firebaseapp.com',
    storageBucket: 'easy--learners.firebasestorage.app',
    measurementId: 'G-0LEV8VW2WC',
  );
}
